### ISSUE TITLE
Support multiple reciever for mail object.

### ISSUE THREAD

**Issue by ozantopal** [bozd4g/CQRS.Sample#1]
https://github.com/bozd4g/CQRS.Sample/blob/master/CQRS.Sample/Models/Mail.cs class is not supporting for multiple reciever for email. 

public string To { get; set; } property's type should be derieved from IEnumerable or smilar interface.

**Comment by bozd4g** [comment]
The To property of Mail class is as follows,
`public IEnumerable<string> To { get; set; }`

Thanks 👍
